## Formulating the problem as an MDP 

In [ ]:
import pandas as pd


In [ ]:
df1 = pd.read_csv('Final_Datasetnew.csv')
df2 = pd.read_csv('Final_Datasetnew2.csv')
data = pd.concat([df1, df2])
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6558 entries, 0 to 4431
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   State       6558 non-null   int64  
 1   Action      6558 non-null   object 
 2   Reward      6558 non-null   int64  
 3   Next_State  6558 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 256.2+ KB


In [ ]:
# Need to label encode the actions 
# Positive - 2
# Neutral - 1
# Negative - 0 

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
data['Action'] = label_encoder.fit_transform(data['Action'])
print(data['Action'].unique())
data.head(5)

[1 2 0]


State  Action  Reward  Next_State
0      1       1      -1         1.0
1      1       1      10         2.0
2      2       1      10         2.0
3      2       1      -1         1.0
4      1       1      10         2.0

## Action 0

In [ ]:
action0 = (data['Action'] == 0).sum()
action1 = (data['Action'] == 1).sum()
action2 = (data['Action'] == 2).sum()

act0st1 = data[(data['Action'] == 0) & (data['State'] == 1)]

act0pr1_1 = data[(data['Action'] == 0) & (data['State'] == 1) & 
              (data['Next_State'] == 1)]              
act0pr1_2 = data[(data['Action'] == 0) & (data['State'] == 1) & 
              (data['Next_State'] == 2)]
act0pr1_3 = data[(data['Action'] == 0) & (data['State'] == 1) & 
              (data['Next_State'] == 3)]
act0pr1_4 = data[(data['Action'] == 0) & (data['State'] == 1) & 
              (data['Next_State'] == 4)] 

pr0_1_1 = len(act0pr1_1)/len(act0st1)
pr0_1_2 = len(act0pr1_2)/len(act0st1)
pr0_1_3 = len(act0pr1_3)/len(act0st1)
pr0_1_4 = len(act0pr1_4)/len(act0st1)

act0st2 = data[(data['Action'] == 0) & (data['State'] == 2)]

act0pr2_1 = data[(data['Action'] == 0) & (data['State'] == 2) & 
              (data['Next_State'] == 1)]
act0pr2_2 = data[(data['Action'] == 0) & (data['State'] == 2) & 
              (data['Next_State'] == 2)]
act0pr2_3 = data[(data['Action'] == 0) & (data['State'] == 2) & 
              (data['Next_State'] == 3)]
act0pr2_4 = data[(data['Action'] == 0) & (data['State'] == 2) & 
              (data['Next_State'] == 4)] 

pr0_2_1 = len(act0pr2_1)/len(act0st2)
pr0_2_2 = len(act0pr2_2)/len(act0st2)
pr0_2_3 = len(act0pr2_3)/len(act0st2)
pr0_2_4 = len(act0pr2_4)/len(act0st2)

act0st3 = data[(data['Action'] == 0) & (data['State'] == 3)]

act0pr3_1 = data[(data['Action'] == 0) & (data['State'] == 3) & 
              (data['Next_State'] == 1)]
act0pr3_2 = data[(data['Action'] == 0) & (data['State'] == 3) & 
              (data['Next_State'] == 2)]
act0pr3_3 = data[(data['Action'] == 0) & (data['State'] == 3) & 
              (data['Next_State'] == 3)]
act0pr3_4 = data[(data['Action'] == 0) & (data['State'] == 3) & 
              (data['Next_State'] == 4)]

pr0_3_1 = len(act0pr3_1)/len(act0st3)
pr0_3_2 = len(act0pr3_2)/len(act0st3)
pr0_3_3 = len(act0pr3_3)/len(act0st3)
pr0_3_4 = len(act0pr3_4)/len(act0st3)

act0st4 = data[(data['Action'] == 0) & (data['State'] == 4)]

act0pr4_1 = data[(data['Action'] == 0) & (data['State'] == 4) & 
              (data['Next_State'] == 1)]
act0pr4_2 = data[(data['Action'] == 0) & (data['State'] == 4) & 
              (data['Next_State'] == 2)]
act0pr4_3 = data[(data['Action'] == 0) & (data['State'] == 4) & 
              (data['Next_State'] == 3)]
act0pr4_4 = data[(data['Action'] == 0) & (data['State'] == 4) & 
              (data['Next_State'] == 4)]

pr0_4_1 = len(act0pr4_1)/len(act0st4)
pr0_4_2 = len(act0pr4_2)/len(act0st4)
pr0_4_3 = len(act0pr4_3)/len(act0st4)
pr0_4_4 = len(act0pr4_4)/len(act0st4)


## Action 1

In [ ]:
act1st1 = data[(data['Action'] == 1) & (data['State'] == 1)]

act1pr1_1 = data[(data['Action'] == 1) & (data['State'] == 1) & 
              (data['Next_State'] == 1)]              
act1pr1_2 = data[(data['Action'] == 1) & (data['State'] == 1) & 
              (data['Next_State'] == 2)]
act1pr1_3 = data[(data['Action'] == 1) & (data['State'] == 1) & 
              (data['Next_State'] == 3)]
act1pr1_4 = data[(data['Action'] == 1) & (data['State'] == 1) & 
              (data['Next_State'] == 4)] 

pr1_1_1 = len(act1pr1_1)/len(act1st1)
pr1_1_2 = len(act1pr1_2)/len(act1st1)
pr1_1_3 = len(act1pr1_3)/len(act1st1)
pr1_1_4 = len(act1pr1_4)/len(act1st1)

act1st2 = data[(data['Action'] == 1) & (data['State'] == 2)]

act1pr2_1 = data[(data['Action'] == 1) & (data['State'] == 2) & 
              (data['Next_State'] == 1)]
act1pr2_2 = data[(data['Action'] == 1) & (data['State'] == 2) & 
              (data['Next_State'] == 2)]
act1pr2_3 = data[(data['Action'] == 1) & (data['State'] == 2) & 
              (data['Next_State'] == 3)]
act1pr2_4 = data[(data['Action'] == 1) & (data['State'] == 2) & 
              (data['Next_State'] == 4)] 

pr1_2_1 = len(act1pr2_1)/len(act1st2)
pr1_2_2 = len(act1pr2_2)/len(act1st2)
pr1_2_3 = len(act1pr2_3)/len(act1st2)
pr1_2_4 = len(act1pr2_4)/len(act1st2)

act1st3 = data[(data['Action'] == 1) & (data['State'] == 3)]

act1pr3_1 = data[(data['Action'] == 1) & (data['State'] == 3) & 
              (data['Next_State'] == 1)]
act1pr3_2 = data[(data['Action'] == 1) & (data['State'] == 3) & 
              (data['Next_State'] == 2)]
act1pr3_3 = data[(data['Action'] == 1) & (data['State'] == 3) & 
              (data['Next_State'] == 3)]
act1pr3_4 = data[(data['Action'] == 1) & (data['State'] == 3) & 
              (data['Next_State'] == 4)]

pr1_3_1 = len(act1pr3_1)/len(act1st3)
pr1_3_2 = len(act1pr3_2)/len(act1st3)
pr1_3_3 = len(act1pr3_3)/len(act1st3)
pr1_3_4 = len(act1pr3_4)/len(act1st3)

act1st4 = data[(data['Action'] == 1) & (data['State'] == 4)]

act1pr4_1 = data[(data['Action'] == 1) & (data['State'] == 4) & 
              (data['Next_State'] == 1)]
act1pr4_2 = data[(data['Action'] == 1) & (data['State'] == 4) & 
              (data['Next_State'] == 2)]
act1pr4_3 = data[(data['Action'] == 1) & (data['State'] == 4) & 
              (data['Next_State'] == 3)]
act1pr4_4 = data[(data['Action'] == 1) & (data['State'] == 4) & 
              (data['Next_State'] == 4)]

pr1_4_1 = len(act1pr4_1)/len(act1st4)
pr1_4_2 = len(act1pr4_2)/len(act1st4)
pr1_4_3 = len(act1pr4_3)/len(act1st4)
pr1_4_4 = len(act1pr4_4)/len(act1st4)

## Action 2

In [ ]:
act2st1 = data[(data['Action'] == 2) & (data['State'] == 1)]

act2pr1_1 = data[(data['Action'] == 2) & (data['State'] == 1) & 
              (data['Next_State'] == 1)]              
act2pr1_2 = data[(data['Action'] == 2) & (data['State'] == 1) & 
              (data['Next_State'] == 2)]
act2pr1_3 = data[(data['Action'] == 2) & (data['State'] == 1) & 
              (data['Next_State'] == 3)]
act2pr1_4 = data[(data['Action'] == 2) & (data['State'] == 1) & 
              (data['Next_State'] == 4)] 

pr2_1_1 = len(act2pr1_1)/len(act2st1)
pr2_1_2 = len(act2pr1_2)/len(act2st1)
pr2_1_3 = len(act2pr1_3)/len(act2st1)
pr2_1_4 = len(act2pr1_4)/len(act2st1)

act2st2 = data[(data['Action'] == 2) & (data['State'] == 2)]

act2pr2_1 = data[(data['Action'] == 2) & (data['State'] == 2) & 
              (data['Next_State'] == 1)]
act2pr2_2 = data[(data['Action'] == 2) & (data['State'] == 2) & 
              (data['Next_State'] == 2)]
act2pr2_3 = data[(data['Action'] == 2) & (data['State'] == 2) & 
              (data['Next_State'] == 3)]
act2pr2_4 = data[(data['Action'] == 2) & (data['State'] == 2) & 
              (data['Next_State'] == 4)] 

pr2_2_1 = len(act2pr2_1)/len(act2st2)
pr2_2_2 = len(act2pr2_2)/len(act2st2)
pr2_2_3 = len(act2pr2_3)/len(act2st2)
pr2_2_4 = len(act2pr2_4)/len(act2st2)

act2st3 = data[(data['Action'] == 2) & (data['State'] == 3)]

act2pr3_1 = data[(data['Action'] == 2) & (data['State'] == 3) & 
              (data['Next_State'] == 1)]
act2pr3_2 = data[(data['Action'] == 2) & (data['State'] == 3) & 
              (data['Next_State'] == 2)]
act2pr3_3 = data[(data['Action'] == 2) & (data['State'] == 3) & 
              (data['Next_State'] == 3)]
act2pr3_4 = data[(data['Action'] == 2) & (data['State'] == 3) & 
              (data['Next_State'] == 4)]

pr2_3_1 = len(act2pr3_1)/len(act2st3)
pr2_3_2 = len(act2pr3_2)/len(act2st3)
pr2_3_3 = len(act2pr3_3)/len(act2st3)
pr2_3_4 = len(act2pr3_4)/len(act2st3)

act2st4 = data[(data['Action'] == 2) & (data['State'] == 4)]

act2pr4_1 = data[(data['Action'] == 2) & (data['State'] == 4) & 
              (data['Next_State'] == 1)]
act2pr4_2 = data[(data['Action'] == 2) & (data['State'] == 4) & 
              (data['Next_State'] == 2)]
act2pr4_3 = data[(data['Action'] == 2) & (data['State'] == 4) & 
              (data['Next_State'] == 3)]
act2pr4_4 = data[(data['Action'] == 2) & (data['State'] == 4) & 
              (data['Next_State'] == 4)]

pr2_4_1 = len(act2pr4_1)/len(act2st4)
pr2_4_2 = len(act2pr4_2)/len(act2st4)
pr2_4_3 = len(act2pr4_3)/len(act2st4)
pr2_4_4 = len(act2pr4_4)/len(act2st4)

In [ ]:
import numpy as np


class MDP:
    '''A simple MDP class.  It includes the following members'''

    def __init__(self, T, R, discount):
        '''Constructor for the MDP class

        Inputs:
        T -- Transition function: |A| x |S| x |S'| array
        R -- Reward function: |A| x |S| array
        discount -- discount factor: scalar in [0,1)

        The constructor verifies that the inputs are valid and sets
        corresponding variables in a MDP object'''

        assert T.ndim == 3, "Invalid transition function: it should have 3 dimensions"
        self.nActions = T.shape[0]
        self.nStates = T.shape[1]
        assert T.shape == (
        self.nActions, self.nStates, self.nStates), "Invalid transition function: it has dimensionality " + repr(
            T.shape) + ", but it should be (nActions,nStates,nStates)"
        assert (abs(T.sum(
            2) - 1) < 1e-5).all(), "Invalid transition function: some transition probability does not equal 1"
        self.T = T
        assert R.ndim == 2, "Invalid reward function: it should have 2 dimensions"
        assert R.shape == (self.nActions, self.nStates), "Invalid reward function: it has dimensionality " + repr(
            R.shape) + ", but it should be (nActions,nStates)"
        self.R = R
        assert 0 <= discount < 1, "Invalid discount factor: it should be in [0,1)"
        self.discount = discount

    def valueIteration(self, initialV, nIterations=np.inf, tolerance=0.01):
        '''Value iteration procedure
        V <-- max_a R^a + gamma T^a V

        Inputs:
        initialV -- Initial value function: array of |S| entries
        nIterations -- limit on the # of iterations: scalar (default: infinity)
        tolerance -- threshold on ||V^n-V^n+1||_inf: scalar (default: 0.01)

        Outputs: 
        V -- Value function: array of |S| entries
        iterId -- # of iterations performed: scalar
        epsilon -- ||V^n-V^n+1||_inf: scalar'''

        V = initialV
        iterId = 0
        epsilon = np.inf
        policy = np.zeros(len(initialV), dtype=int)

        """
        print("===========================================================================")
        print("Executing Value Iteration")
        print("--------------------------------------------")
        """

        while iterId < nIterations and epsilon > tolerance:
            Ta_V = np.matmul(self.T, V)
            gamma_Ta_V = self.discount * Ta_V
            all_possible_values = self.R + gamma_Ta_V
            policy = np.argmax(all_possible_values, axis=0)  # Choose the best actions for each state, policy means keep
            V_new = np.amax((all_possible_values), axis=0)  # Choose the best action values for each state
            # np.round/np.around does not work for 0.5 so not reducing to 2 decimal places
            V_diff = (V_new - V)
            V = V_new
            epsilon = np.linalg.norm(V_diff, np.inf)
            #computes the maximum absolute value of the elements in the V_diff array and stores the result in the variable epsilon
            #print("Iteration : " + str(iterId) + " V : " + str(V) + " Policy: " + str(policy) + " epsilon: " + str(epsilon))
            iterId = iterId + 1

        """
        print("--------------------------------------------")
        print("Final State values after " + str(iterId) + " iterations , V: " + str(V) + " Policy: " + str(policy))
        print("===========================================================================")
        """

        return [V, iterId, epsilon]

    def extractPolicy(self, V):
        '''Procedure to extract a policy from a value function
        pi <-- argmax_a R^a + gamma T^a V

        Inputs:
        V -- Value function: array of |S| entries

        Output:
        policy -- Policy: array of |S| entries'''

        """
        print("***************************************************************")
        print("Executing Policy Extraction")
        print("--------------------------------------------")
        """

        all_possible_values = (self.R + (self.discount*(np.matmul(self.T, V))))  # Get values for all possible state transition in this state

        """
        print("All Values for All possible state transition: ")
        print(all_possible_values)
        """

        policy = np.argmax(all_possible_values, axis=0)  # Choose the best actions for each state, policy means keep

        """
        print("Extracted Policy : " + str(policy))
        print("--------------------------------------------")
        """

        """
        # track of action chosen at timestamp t, instead of choosing only value
        max_values = [all_possible_values[policy[i]][i] for i in range(len(policy))]
        print("Values Corresponding to Selected Policies: " + str(max_values))
        print("***************************************************************")
        """

        return policy

    def evaluatePolicy(self, policy):
        '''Evaluate a policy by solving a system of linear equations
        V^pi = R^pi + gamma T^pi V^pi

        Input:
        policy -- Policy: array of |S| entries

        Ouput:
        V -- Value function: array of |S| entries'''

        """
        print("***************************************************************")
        print("Executing Policy Evaluation")
        print("--------------------------------------------")
        print("Policy : " + str(policy))
        print("Evaluating a policy by solving a system of linear equations")
        """

        R_policy = np.array([self.R[policy[i]][i] for i in range(len(policy))])
        T_policy = np.array([self.T[policy[i]][i] for i in range(len(policy))])
        gamma_T_policy = self.discount * T_policy
        assert gamma_T_policy.shape[0] == gamma_T_policy.shape[1], "gamma_T_policy matrix should be square"
        V = np.matmul(np.linalg.inv(np.identity(len(policy)) - gamma_T_policy), R_policy)

        """
        print("V : " + str(V))
        print("***************************************************************")
        """

        return V

    def policyIteration(self, initialPolicy, nIterations=np.inf):
        '''Policy iteration procedure: alternate between policy
        evaluation (solve V^pi = R^pi + gamma T^pi V^pi) and policy
        improvement (pi <-- argmax_a R^a + gamma T^a V^pi).

        Inputs:
        initialPolicy -- Initial policy: array of |S| entries
        nIterations -- limit on # of iterations: scalar (default: inf)

        Outputs: 
        policy -- Policy: array of |S| entries
        V -- Value function: array of |S| entries
        iterId -- # of iterations peformed by modified policy iteration: scalar'''

        policy = initialPolicy  # np.zeros(self.nStates)
        V = np.zeros(self.nStates)
        iterId = 0

        """
        print("===========================================================================")
        print("Executing Policy Iteration")
        print("--------------------------------------------")
        """

        while iterId < nIterations:
            V = self.evaluatePolicy(policy)
            #print("Iteration : " + str(iterId) + " V : " + str(V) + " policy : " + str(policy))

            policy_new = self.extractPolicy(V)
            iterId = iterId + 1

            if np.array_equal(policy_new, policy):
                break

            policy = policy_new

        """
        print("Iteration : " + str(iterId) + " V : " + str(V) + " policy : " + str(policy))
        print("--------------------------------------------")
        print("Final policy after " + str(iterId) + " iterations , policy: " + str(policy))
        print("===========================================================================")
        """

        return [policy, V, iterId]

    def evaluatePolicyPartially(self, policy, initialV, nIterations=np.inf, tolerance=0.01):
        '''Partial policy evaluation:
        Repeat V^pi <-- R^pi + gamma T^pi V^pi

        Inputs:
        policy -- Policy: array of |S| entries
        initialV -- Initial value function: array of |S| entries
        nIterations -- limit on the # of iterations: scalar (default: infinity)
        tolerance -- threshold on ||V^n-V^n+1||_inf: scalar (default: 0.01)

        Outputs: 
        V -- Value function: array of |S| entries
        iterId -- # of iterations performed: scalar
        epsilon -- ||V^n-V^n+1||_inf: scalar'''

        # temporary values to ensure that the code compiles until this
        # function is coded
        V = initialV  # np.zeros(self.nStates)
        iterId = 0
        epsilon = np.inf

        """
        print("***************************************************************")
        print("Executing Partial Policy Evaluation")
        print("--------------------------------------------")
        print("Policy : " + str(policy))
        print("Evaluating a policy by repeating " + str(nIterations) + " times.")
        print("Iteration : " + str(iterId) + " V : " + str(V) + " Policy: " + str(policy))
        """

        while iterId < nIterations and epsilon > tolerance:
            iterId = iterId+1
            R_policy = np.array([self.R[policy[i]][i] for i in range(len(policy))])
            T_policy = np.array([self.T[policy[i]][i] for i in range(len(policy))])
            Vnew = R_policy + (self.discount * np.matmul(T_policy, V))
            epsilon = np.linalg.norm((Vnew-V), np.inf)
            V = Vnew

            #print("Iteration : " + str(iterId) + " V : " + str(V) + " Policy: " + str(policy) + " epsilon : " + str(epsilon))

        """
        print("V : " + str(V))
        print("***************************************************************")
        """

        return [V, iterId, epsilon]

    def modifiedPolicyIteration(self, initialPolicy, initialV, nEvalIterations=5, nIterations=np.inf, tolerance=0.01):
        '''Modified policy iteration procedure: alternate between
        partial policy evaluation (repeat a few times V^pi <-- R^pi + gamma T^pi V^pi)
        and policy improvement (pi <-- argmax_a R^a + gamma T^a V^pi)

        Inputs:
        initialPolicy -- Initial policy: array of |S| entries
        initialV -- Initial value function: array of |S| entries
        nEvalIterations -- limit on # of iterations to be performed in each partial policy evaluation: scalar (default: 5)
        nIterations -- limit on # of iterations to be performed in modified policy iteration: scalar (default: inf)
        tolerance -- threshold on ||V^n-V^n+1||_inf: scalar (default: 0.01)

        Outputs: 
        policy -- Policy: array of |S| entries
        V -- Value function: array of |S| entries
        iterId -- # of iterations peformed by modified policy iteration: scalar
        epsilon -- ||V^n-V^n+1||_inf: scalar'''

        # temporary values to ensure that the code compiles until this
        # function is coded
        policy = initialPolicy
        V = initialV
        iterId = 0
        epsilon = np.inf

        """
        print("===========================================================================")
        print("Executing Modified Policy Iteration")
        print("--------------------------------------------")
        print("Iteration : " + str(iterId) + " policy : " + str(policy))
        """

        while iterId < nIterations and epsilon > tolerance:
            iterId = iterId + 1
            Vn, _ , _  = self.evaluatePolicyPartially(policy, V, nEvalIterations, tolerance)
            #print("Vn : " + str(Vn))
            all_possible_values = (self.R + (self.discount * np.matmul(self.T,Vn)))  # Get values for all possible state transition in this state
            policy = np.argmax(all_possible_values, axis=0)  # Choose the best actions for each state, policy means keep

            Vn_plus_1 = [all_possible_values[policy[i]][i] for i in range(len(policy))]
            V_diff = (Vn_plus_1 - Vn)
            V = Vn_plus_1
            epsilon = np.linalg.norm(V_diff, np.inf)
            #print("Iteration : " + str(iterId) + " policy : " + str(policy))

        """
        print("--------------------------------------------")
        print("Final policy after " + str(iterId) + " iterations , policy: " + str(policy))
        print("===========================================================================")
        """

        return [policy, V, iterId, epsilon]


In [ ]:
''' Construct simple MDP as described in Lecture 1b Slides 17-18'''
# Transition function: |A| x |S| x |S'| array
T = np.array([[[pr0_1_1,pr0_1_2,pr0_1_3,pr0_1_4],[pr0_2_1,pr0_2_2,pr0_2_3,pr0_2_4],
               [pr0_3_1,pr0_3_2,pr0_3_3,pr0_3_4],[pr0_4_1,pr0_4_2,pr0_4_3,pr0_4_4]],
              [[pr1_1_1,pr1_1_2,pr1_1_3,pr1_1_4],[pr1_2_1,pr1_2_2,pr1_2_3,pr1_2_4],
               [pr1_3_1,pr1_3_2,pr1_3_3,pr1_3_4],[pr1_4_1,pr1_4_2,pr1_4_3,pr1_4_4]],
              [[pr2_1_1,pr2_1_2,pr2_1_3,pr2_1_4],[pr2_2_1,pr2_2_2,pr2_2_3,pr2_2_4],
               [pr2_3_1,pr2_3_2,pr2_3_3,pr2_3_4],[pr2_4_1,pr2_4_2,pr2_4_3,pr2_4_4]]])
# Reward function: |A| x |S| array
R = np.array([[-1, 10, 25, 50],[-1, 10, 25, 50],[-1, 10, 25, 50]])
# Discount factor: scalar in [0,1)
discount = 0.9        
# MDP object
mdp = MDP(T,R,discount)

In [ ]:
print(T.round(3))

[[[0.398 0.304 0.216 0.082]
  [0.202 0.441 0.282 0.075]
  [0.115 0.345 0.403 0.137]
  [0.157 0.241 0.422 0.181]]

 [[0.331 0.352 0.248 0.068]
  [0.156 0.474 0.293 0.076]
  [0.113 0.363 0.415 0.109]
  [0.133 0.273 0.411 0.184]]

 [[0.495 0.297 0.168 0.04 ]
  [0.179 0.538 0.243 0.04 ]
  [0.309 0.336 0.289 0.066]
  [0.133 0.556 0.244 0.067]]]


In [ ]:
'''Test each procedure'''
[V,nIterations,epsilon] = mdp.valueIteration(initialV=np.zeros(mdp.nStates))
policy = mdp.extractPolicy(V)
print("V : " , V.round(3))
print("nIterations : " + str(nIterations))
print("Policy : " + str(policy))

V :  [150.513 164.936 185.041 211.898]
nIterations : 72
Policy : [1 1 0 1]


In [ ]:
V = mdp.evaluatePolicy(np.array([1,0,1,0]))
print("Value corresponding to policy [1,0,1,0]: " + str(V))

V = mdp.evaluatePolicy(np.array([2,2,2,1]))
print("Value corresponding to policy [0,1,1,1]: " + str(V))

Value corresponding to policy [1,0,1,0]: [144.7717929  158.23464583 178.14885809 205.8092465 ]
Value corresponding to policy [0,1,1,1]: [106.32655538 123.13235676 137.91020339 172.41315478]


In [ ]:
[policy,V,iterId] = mdp.policyIteration(np.array([0,0,0,0]))
print("V : " + str(V))
print("nIterations : " + str(iterId))
print("Epsilon : " + str(policy))

V : [150.60117771 165.0247759  185.12940029 211.98662109]
nIterations : 2
Epsilon : [1 1 0 1]


In [ ]:
[V,iterId,epsilon] = mdp.evaluatePolicyPartially(np.array([1,0,1,0]),np.array([0,10,0,13]))
[policy,V,iterId,tolerance] = mdp.modifiedPolicyIteration(np.array([1,0,1,0]),np.array([0,10,0,13]))
print("V : " + str(V))
print("nIterations : " + str(iterId))
print("Policy : " + str(policy))

V : [150.51337920236205, 164.93697739051854, 185.04160178266346, 211.8988225857995]
nIterations : 12
Policy : [1 1 0 1]
